server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  #--------------------------charset--------------------------
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  mvc:
    static-path-pattern: /**
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    servlet:
      content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/supermarket?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
mybatis:
  config-location: classpath:mapper/config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml


